### ISSUE TITLE
schedule at sunset / sunrise

### ISSUE THREAD

**Issue by brightdroid** [efficiosoft/hass-apps#27]
First, thanks for this great scheduler :+1: 

I'd like to see support of sunset/sunrise and offsets like in appdaemon (https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#time)

So one could switch on garden lights at sunset and switch them off at sunrise. (and may be with an offset)
```yaml
      schedule:
        # switch on 30 minutes before sunset
        - { v: "on", start: "sunset - 00:30:00" }
        # switch off 5 minutes after sunrise
        - { v: "off", start: "sunrise + 00:05:00" }
```

Thanks

**Comment by efficiosoft** [comment]
I'm closing this for now, maybe direct support will be added at a later time.

**Comment by brightdroid** [comment]
Ok, thanks the tip with `sun.sun` will probably solve my scheduling "problem".

**Comment by bachya** [comment]
@brightdroid In case you need it (or for others who stumble upon this issue), here's how I solved this problem for our backyard light switch (which uses different schedules for weeknights and weekend nights):

```
outdoor_lights_schedule:
  module: hass_apps_loader
  class: SchedyApp

  actor_type: switch

  expression_environment: |
    def is_sun_down():
      return state("sun.sun") == "below_horizon"

  rooms:

    backyard:

      actors:
        switch.backyard_lights:

      rescheduling_delay: 0

      schedule:
        - v: "on"
          rules:
            - x: "Skip() if is_sun_down() else Break()"
            - {start: "17:00", end: "21:30", weekdays: "1-4, 7"}
            - {start: "17:00", end: "23:00", weekdays: 5-6}
        - v: "off"

  watched_entities:
    - sun.sun
```

A few key points about how this works:

* In order to not have weird situations with midnights, each rule sets an arbitrary starting time that I know will be before sunset, regardless of the season.
* Each schedule is skipped if the sun isn't down (by watching the `sun.sun` entity).
* I watch the state of `sun.sun` – as soon as it changes, the schedules are re-evaluated and if its down, the lights turn on.

**Comment by brightdroid** [comment]
Thanks, but I found a perfect solution using the sun elevation:
```
  schedule_append:
    # default value
    - v: "off"

  watched_entities:
    - "sun.sun:elevation"

  rooms:
    backyard:
      friendly_name: Backyard
      actors:
        switch.rearentrancelight:
      schedule:
        - x: "'on' if float(state('sun.sun', 'elevation')) <= -1.0 else Skip()"
```
