### ISSUE TITLE
[schedy] Reschedule room temperature after window is closed with delay

### ISSUE THREAD

**Issue by insajd** [efficiosoft/hass-apps#30]
Hello, I have this config for my rooms, and the fact that it reacts immediately when window is open - is awesome!
But, I want it to start heating the room again with delay, only after 5-10 minutes that window has been closed, not immediately.
How can I do that?
```
  rooms:
    bedroom:
      schedule:
      - x: ("OFF") if is_on('input_boolean.schedy_off_with_windows') else Skip()
```
