### ISSUE TITLE
[schedy] Race condition with OVERLAY and rescheduling_delay

### ISSUE THREAD

**Issue by tristone-cz** [efficiosoft/hass-apps#35]
If temperature is set manually at thermostat (OVERLAY applies) and then window is opened behavior is correct, valve goes OFF.

Then two cases:
a) If window is closed inside the resheduling interval thermostat returns fine to the manual value and once rescheduling expires it continues according to schedule. This is correct behavior.
b) Problem occurs once the window is opened for longer time and the rescheduling expiration is missed. Then after window closure the value is returned to the manual one instead of scheduled one. And during each evaluation of the schedule later on it is left untouched.

I attached logs. They are filter just for one room, others were removed for easier reading.
[schedy.log](https://github.com/efficiosoft/hass-apps/files/3472693/schedy.log)

Following times are interesting:
15:40:43 - manual change on thermostat from 16 to 17 °C
15:42:25 - window opened
15:44:11 - first re-evalution after rescheduling delay expired (happening every minute)
15:44:45 - window closed, thermostat returned to 17 °C
15:45:11 - re-evaluation of the schedule, not returned to 16 °C even here

Relevant parts of the config during the tess:
```
  schedule_prepend:
  # Master switch
  - x: "OFF if is_off('input_boolean.heating_enabled') else Skip()"
  # Open windows / doors
  - x: "Mark(OFF, Mark.OVERLAY) if not is_empty(filter_entities('binary_sensor', state='on', window_room=room_name)) else Skip()"

  rooms:
    bedroom:
      rescheduling_delay: 3
      actors:
        climate.eurotronic_eur_spiritz_wall_radiator_thermostat_heat:

      schedule:
      <SKIPPED RULES>
      # At all other times, set temperature to low value
      - x: state("input_number.bedroom_low_temperature")
```

Regards,
Jaroslav
