### ISSUE TITLE
[schedy] Warnings about unsupported HVAC mode

### ISSUE THREAD

**Issue by chbndrhnns** [efficiosoft/hass-apps#41]
I am using Homematic IP thermostates and when following your tutorial, I see these warnings for each thermostate:

```
2019-12-11 18:41:43.076734 WARNING schedy_heating: !!! [R:arbeitszimmer] [A:climate.arbeitszimmer] Thermostat doesn't seem to support the HVAC mode off, supported modes are: ['auto', 'heat']. Please check your config!
2019-12-11 18:41:43.082500 ERROR schedy_heating: !!! [R:arbeitszimmer] [A:climate.arbeitszimmer] Unknown HVAC mode 'auto', ignoring thermostat.
```

The state YAML for these thermostates looks like that:

```yaml
hvac_modes:
  - auto
  - heat
current_temperature: 19.9
min_temp: 5
max_temp: 30
temperature: 17
preset_mode: null
preset_modes:
  - none
  - boost
model_type: HmIP-Heating-Group
is_group: true
friendly_name: Arbeitszimmer
supported_features: 17
```

Am I doing something wrong or what is your advice on these warnings?

**Comment by efficiosoft** [comment]
Hi,

This is no bug. It simply tells you that your thermostat doesn't support to be turned off by setting it to some specific HVAC mode. Some thermostat models simply do so.

You should disable HVAC mode support in your case and always leave the thermostat in a fixed mode. The [docs](https://hass-apps.readthedocs.io/en/stable/apps/schedy/actors/thermostat/index.html#configuration) tell you how to do this.

Best regards
Robert

**Comment by u20p17** [comment]
Hi,
I am trying to use schedy for my zwave thermostats, which I already can manually control via Home Assistant. I Started with the official tutorial and now have a question. If I add

```
# In the following config block, you may define templates with
  # settings that affect multiple actors in your setup. These can then be
  # used as a starting point for the configuration of individual actors.
  # Nested inclusion of templates is possible as well.
  actor_templates:

    # By default, an actor inherits its settings from the "default" template.
    default:
    #delta: 0.0
      off_temp: 7
      **supports_hvac_modes: true**
      hvac_mode_on: heat
      hvac_mode_off: 'OFF' 
```
I recieve the following warning:
```
2021-05-24 08:34:39.317374 INFO schedy: --> [R:buero] [A:climate.devolo_thermostat_09356_2] Received value of 17.0��.
2021-05-24 08:34:39.300505 WARNING schedy: !!! [R:buero] [A:climate.devolo_thermostat_09356_2] Thermostat doesn't seem to support the HVAC mode OFF, supported modes are: ['heat']. Please check your config!
```

If I put  **supports_hvac_modes: false** then the waring looks like this:
```
2021-05-24 08:37:23.130981 INFO schedy: --> [R:buero] [A:climate.devolo_thermostat_09356_2] Received value of 17.0��.
2021-05-24 08:37:23.118350 WARNING schedy: !!! [R:buero] [A:climate.devolo_thermostat_09356_2] HVAC mode support has been disabled, but the modes ['heat'] seem to be supported. Maybe disabling it was a mistake?
```

Now I am not sure if I should deactivate it and just irgnore the warning? Or is there a cleaner solution for this?

BR
