### ISSUE TITLE
[schedy] Switch state case sensitivity

### ISSUE THREAD

**Issue by tabnul** [efficiosoft/hass-apps#43]
There seems to be an issue or combination problem between my ikea devices, HAS and schedy.
The schedy Switch generic actor expects values "off" and "on".
However the ikea switches (zigbee2mqtt) push those values uppercase ("OFF" and "ON")
HAS handles this fine.

In schedy i get the below error on state change of the device:
`2020-01-01 23:37:37.019442 ERROR schedy_test: !!! [R:test_fulltime] [A:switch.0x000d6ffffeaa2589_switch] State 'ON' for slot 0 is not known by this generic actor, ignoring state change.`

Strangly it does switch sometimes, only ON so it seems.

I cannot set the values to uppercase in the config because it won't accept this (for the same reason).

Workaround i currently have is to give each device its own HASS group and use the group in schedy.  Groups state are lower case by default (but unreliable with multiple devices in it because the state is not consistent with all devices - off especially)

**Comment by efficiosoft** [comment]
Hi,

Thanks for reporting.

I think your best bet would be to create a custom actor template based on the `generic` actor type, basically what the `switch` actor looks like, but with the values in upper case.

I could of course include another actor type for this natively, but I think upper case on/off is quite uncommon.

BTW, can't you just use `state_template` in the mqtt switch config to make the value lowercase? Seems like the cleanest solution to me while thinking about it.

Best regards
Robert

**Comment by tabnul** [comment]
> Hi,
> 
> Thanks for reporting.
> 
> I think your best bet would be to create a custom actor template based on the `generic` actor type, basically what the `switch` actor looks like, but with the values in upper case.
> 

Thanks, is there an example available for the custom actors ? Allready looked into it but was not able to figure out how this works.


> I could of course include another actor type for this natively, but I think upper case on/off is quite uncommon.
> 
> BTW, can't you just use `state_template` in the mqtt switch config to make the value lowercase? Seems like the cleanest solution to me while thinking about it.
> 

The uppercase 'issue' seems to be generic MQTT behavior (default payload IS in uppercase, i think the problem is more widespread than just the Ikea switches.

**Comment by efficiosoft** [comment]
> Thanks, is there an example available for the custom actors ? Allready looked into it but was not able to figure out how this works.

Ah, my bad. I meant to use the `generic` actor type, not `custom`.

> The uppercase 'issue' seems to be generic MQTT behavior (default payload IS in uppercase, i think the problem is more widespread than just the Ikea switches.

Sure, but there is the option to provide a template for processing the MQTT state payload into a value to be set as the entity state. This option is called `state_payload` and a value of `"{{ value|lower }}"` should do the trick.

**Comment by efficiosoft** [comment]
Did the `state_template` resolve the issue?

**Comment by tabnul** [comment]
Hi, at the end i converted the schedules to hass automations. I didnt want to change default behaviour of zigbee2mqtt.  
The generic actor was unfortunately too complex for me to figure out.

**Comment by efficiosoft** [comment]
Ah, I'm sure I can help you with that. I added the config you'd have to use with the generic actor to get the behavior of the switch actor [to the docs](https://hass-apps.readthedocs.io/en/latest/apps/schedy/actors/switch/index.html). It should be easy to adapt to your needs now.

And I also updated [this chapter](https://hass-apps.readthedocs.io/en/latest/apps/schedy/concept.html) to make it more clear why you might not want to use automations for scheduling. Maybe you want to read that as well.

Just ask if you've got further questions.

**Comment by tabnul** [comment]
Thanks for your help.
I found out the hard way why automations are a pain.. loads of code needed for basic actions. I do use the fact that ikea zigbee devices 'call home' every hour so if a switch did not switch effectively (or someone turned it on manually) it will still switch in the desired state. 

I made the following test configuration, no errors are thrown but it is not working.
I probably do something majorly wrong here.


```
schedy_achterdeur_test:  
  module: hass_apps_loader
  class: SchedyApp
  actor_type: generic
  actor_templates:
    default:
      attributes:
      - attribute: state
        values:
          "ON":
            service: homeassistant.turn_on
          "OFF":
            service: homeassistant.turn_off
    schedule_prepend:
    schedule_append:
    schedule_snippets:
    rooms:
      lamp_achterdeur_test:
        friendly_name: lamp_achterdeur_test
        allow_manual_changes: false
        rescheduling_delay: 1
        actors:
          light.0xec1bbdfffea7b8a7_light:
        schedule:
        - value: "OFF"
          start: "12:00"
          end: "23:00"
        - value: "ON"
        watched_entities:
      statistics:
```

**Comment by efficiosoft** [comment]
Hm, what does "not working" mean? I can't see anything problematic in here...

What happens if you switch the `"ON"` and `"OFF"` and save the config? Does the light toggle then and what does Schedy say in the log then?

**Comment by efficiosoft** [comment]
Ah, what makes no sense is disabling `allow_manual_changes` and setting a `rescheduling_delay` at the same time. Obviously, these two contradict eachother.

**Comment by tabnul** [comment]
Thanks for your reply. I had this combination working in the switch actor, but i removed it since it makes indeed no sense.
I swapped states around, and the state does not get detected. 
I also tried mapping to the group , doesnt work either.
Currently i have this in the configuration:

```
schedy_achterdeur_test:  
  module: hass_apps_loader
  class: SchedyApp
  actor_type: generic
  actor_templates:
    default:
      attributes:
      - attribute: state
        values:
          "ON":
            service: homeassistant.turn_on
          "OFF":
            service: homeassistant.turn_off
    schedule_prepend:
    schedule_append:
    schedule_snippets:
    rooms:
      lamp_achterdeur_test:
        friendly_name: lamp_achterdeur_test
        allow_manual_changes: false
        actors:
          light.0xec1bbdfffea7b8a7_light:
        schedule:
        - value: "ON"
          start: "08:00"
          end: "23:00"
        - value: "OFF"
        watched_entities:
      statistics:
```

This is the log:
```
2020-01-06 10:07:24.132481 INFO AppDaemon: Reading config
2020-01-06 10:07:24.174231 INFO AppDaemon: /config/appdaemon/apps/schedy.yaml added or modified
2020-01-06 10:07:24.174516 INFO AppDaemon: App 'schedy_achterdeur_test' changed
2020-01-06 10:07:24.175405 INFO AppDaemon: Terminating schedy_achterdeur_test
2020-01-06 10:07:24.175852 INFO AppDaemon: Initializing app schedy_achterdeur_test using class SchedyApp from module hass_apps_loader
2020-01-06 10:07:24.178625 INFO schedy_achterdeur_test: *** Welcome to schedy 0.7.0, running on AppDaemon 3.0.5.
2020-01-06 10:07:24.181060 INFO schedy_achterdeur_test: *** 
2020-01-06 10:07:24.183455 INFO schedy_achterdeur_test: *** This is an app from the hass-apps package.
2020-01-06 10:07:24.185818 INFO schedy_achterdeur_test: ***   DOCS: https://hass-apps.readthedocs.io/en/stable/
2020-01-06 10:07:24.188187 INFO schedy_achterdeur_test: *** 
2020-01-06 10:07:24.190589 INFO schedy_achterdeur_test: *** You like this app, want to honor the effort put into
2020-01-06 10:07:24.192952 INFO schedy_achterdeur_test: *** it, ensure continuous development and support?
2020-01-06 10:07:24.195307 INFO schedy_achterdeur_test: *** Then please consider making a donation.
2020-01-06 10:07:24.197659 INFO schedy_achterdeur_test: ***   DONATE: https://hass-apps.readthedocs.io/en/stable/#donations
2020-01-06 10:07:24.200048 INFO schedy_achterdeur_test: *** Thank you very much and enjoy schedy!
2020-01-06 10:07:24.202411 INFO schedy_achterdeur_test: *** 
2020-01-06 10:07:24.207675 INFO schedy_achterdeur_test: --- Actor type is: 'generic'
2020-01-06 10:07:24.214440 INFO schedy_achterdeur_test: *** Initialization done.
```

this is the current state (as you can see, HAS makes the state lowercase)
![state](https://user-images.githubusercontent.com/16493960/71808126-3fe8a080-306d-11ea-9383-3ab8d4cc8fd3.png)
