### ISSUE TITLE
[Schedy] Using attributes on actor type generic2 throws errors

### ISSUE THREAD

**Issue by SeaquestNet** [efficiosoft/hass-apps#50]
Hi!

Im trying to use the new generic2 actor type with the custom attributes to get tuple values. It throws errors though and doesn't seem to fill placeholder.

Error:
```
2020-03-17 22:30:00.408621 ERROR schedy_lights: !!! [R:Gillestugan] [A:light.gillestugan_lights] Couldn't format service data '{attr2}' with values {'entity_id': 'light.gillestugan_lights', 'attr1': 'on', 'attr2': 64}: KeyError('attr2'), omitting data.
2020-03-17 22:30:00.409955 INFO schedy_lights: <-- [R:Gillestugan] [A:light.gillestugan_lights] Calling service 'light/turn_on', data = {'param2': '{attr2}', 'entity_id': 'light.gillestugan_lights'}.
```

Configuration:
```
actor_templates:
  default:
    template: light

  light:
    attributes:
      - attribute: state
      - attribute: brightness
    values:
      - value: ["on", "*"]
        calls:
          - service: light.turn_on
            data:
              brightness: "{attr2}"
            include_entity_id: true
      - value: ["off", "*"]
        calls:
          - service: light.turn_off
      - value: [None]
        calls:
          - service: light.turn_off
    send_retries: 1
    ignore_case: true
```
